const GET_BASIC_PENDING = 'GET_BASIC_PENDING';
const GET_BASIC_FULFILLED = 'GET_BASIC_FULFILLED';
const GET_BASIC_REJECTED = 'GET_BASIC_REJECTED';

export default {
  GET_BASIC_PENDING,
  GET_BASIC_FULFILLED,
  GET_BASIC_REJECTED
};
